//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SicoreQMS.Common.Models.Operation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod_ProcessItem
    {
        public string Id { get; set; }
        public string ProdId { get; set; }
        public string ProdProcessId { get; set; }
        public string ProdName { get; set; }
        public string ProdType { get; set; }
        public string Lot { get; set; }
        public string QualityLevel { get; set; }
        public string ModelName { get; set; }
        public Nullable<int> ModelSort { get; set; }
        public string ProdProcessCard { get; set; }
        public string ProcessType { get; set; }
        public string ProdStandard { get; set; }
        public string CheckStandard { get; set; }
        public Nullable<int> InputQty { get; set; }
        public Nullable<int> OutQty { get; set; }
        public string Operator { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> IsComplete { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public string BeginRemark { get; set; }
        public string EndRemark { get; set; }
        public string OperatorName { get; set; }
        public string EquipmentId { get; set; }
        public string EquipmentList { get; set; }
        public string UDF001 { get; set; }
        public string UDF002 { get; set; }
        public string UDF003 { get; set; }
        public string UDF004 { get; set; }
        public string UDF005 { get; set; }
        public string UDF006 { get; set; }
        public string File001 { get; set; }
        public string File002 { get; set; }
        public byte[] Image1 { get; set; }
        public byte[] Image2 { get; set; }
        public byte[] Image3 { get; set; }
    }
}
