//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SicoreQMS.Common.Models.Operation
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProdInfo
    {
        public string Id { get; set; }
        public string ProdName { get; set; }
        public string ProdType { get; set; }
        public Nullable<int> ProdStatus { get; set; }
        public string ProdLot { get; set; }
        public string CheckLot { get; set; }
        public string QualityLevel { get; set; }
        public string CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ParentId { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Prodstandard { get; set; }
        public string TestLot { get; set; }
        public string TestType { get; set; }
        public string ProdNumber { get; set; }
        public Nullable<int> OriginQty { get; set; }
        public string TestNo { get; set; }
        public string ProdNo { get; set; }
        public string MoNo { get; set; }
    }
}
