//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SicoreQMS.Common.Models.Operation
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestModelItem
    {
        public string Id { get; set; }
        public string ModelId { get; set; }
        public string ModelName { get; set; }
        public string ExperimentItemNo { get; set; }
        public string ExperimentItemName { get; set; }
        public string ExperimentItemStandard { get; set; }
        public string ExperimentItemConditions { get; set; }
        public string ExperimentItemWI { get; set; }
        public Nullable<int> ExperimentItemQty { get; set; }
        public string ExperimentItemNumber { get; set; }
        public Nullable<int> ExperimentItemRank { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string CreateUserNo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifyUserNo { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public string ItemDesc { get; set; }
    }
}
