//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SicoreQMS.Common.Models.Operation
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestProcess
    {
        public string Id { get; set; }
        public string ModelTypeId { get; set; }
        public string ProdName { get; set; }
        public string ProdType { get; set; }
        public string ProdLot { get; set; }
        public string Prodstandard { get; set; }
        public string TestLot { get; set; }
        public string TestType { get; set; }
        public string ProdNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<bool> Isdeletd { get; set; }
        public Nullable<bool> CompleteStatus { get; set; }
        public string ProdId { get; set; }
    }
}
